version: "3.1"
services:
  develop:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/urbanicola_api:latest
    command: bash
    volumes:
      - $PWD:/workdir
      - $PWD/tests/data:/workdir/data
  urbanicola_api:
    image: nepolin/urbanicola_api:latest
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - $PWD:/workdir
    ports:
      - "6969:80"